export interface GalleryItem {
  src: string
  alt: string
  caption?: string
}

export interface Testimonial {
  quote: string
  author: string
  role: string
}

export interface CaseStudy {
  slug: string
  number: string
  title: string
  subtitle: string
  type: string
  domain: string
  status: string
  color: string
  bgGradient: string
  accent: string
  lightBg: string
  tldr: string
  problem: string
  role: string[]
  research: string
  solution: string
  results: { metric: string; before: string; after: string }[]
  learnings: string[]
  pdfFile: string
  prdFile?: string
  heroImage?: string
  heroVideo?: string
  logo?: string
  gallery?: GalleryItem[]
  prototypeUrl?: string
  liveUrl?: string
  embedUrl?: string
  figmaUrl?: string
  wireframes?: GalleryItem[]
  techStack?: string[]
  timeline?: string
  team?: string
  testimonial?: Testimonial
}

export const caseStudies: CaseStudy[] = [
  {
    slug: 'fuds-digital-platform',
    number: '01',
    title: 'Fuds International',
    subtitle: '0→1 Digital Platform',
    type: 'Built & Shipped',
    domain: 'E-Commerce · Home Services',
    status: 'Live',
    color: '#1e40af',
    bgGradient: 'linear-gradient(160deg, #0f172a 0%, #1e3a5f 40%, #1e40af 100%)',
    accent: '#f59e0b',
    lightBg: '#eff6ff',
    tldr: 'A 10-year-old offline security business had zero digital presence and a broken operations process. I built both the customer-facing Shopify website and an internal booking system together — because solving one without the other would have failed. Result: 3.5× lead growth, 60% conversion, 40% retention.',
    problem: 'Fuds International had been operating since 2013 — 2,500+ completed projects, 3,000+ clients, strong offline reputation. But the business was entirely invisible online. No inbound digital channel, sales dependent on outbound calls, no pricing transparency, and zero data on customer acquisition or conversion.',
    role: [
      'End-to-end product ownership in an 8-person company',
      'Figma wireframes, information architecture across 7 service lines',
      'User research: interviews + heatmap analysis',
      'Google Analytics setup and funnel tracking',
      'Shopify build coordination with one developer',
      'PRD writing using 8-section framework',
    ],
    research: 'Conducted user interviews and heatmap analysis. Trust was the #1 conversion barrier — not price, not availability. Mobile users were dropping off at the date-picker (38% abandonment).',
    solution: 'Built a Shopify website across 7 service lines, 10+ product categories, 9 brand partners. Key decisions: upfront pricing on every listing (no competitor showed pricing), trust signals (2,500+ projects badge, brand partner logos), Aadhaar-verified technician credentials, Book a Meet appointment flow. Post-launch: simplified booking form from complex multi-field to 4 fields only (Name, Phone, Service, Location) — 2.5× submission lift.',
    results: [
      { metric: 'Monthly inbound leads', before: '20', after: '70 (3.5×)' },
      { metric: 'Weekly form submissions', before: '5–7', after: '12–18 (2.5×)' },
      { metric: 'Lead-to-paid-job conversion', before: 'Unknown', after: '60%' },
      { metric: 'Repeat customer retention', before: 'Unknown', after: '~40%' },
    ],
    learnings: [
      'Solve the full journey, not the obvious step — the real product was a complete digital + operational system',
      'Trust is a product decision, not a design decision — showing pricing, credentials, and project counts directly answered the #1 conversion barrier',
      'Small UX fixes can have outsized impact — one date-picker removal led to 2.5× form submissions',
    ],
    pdfFile: '/pdfs/01-Fuds-Digital-Platform.pdf',
    prdFile: '/pdfs/prds/01-Fuds-Digital-Platform.pdf',
    heroImage: '/images/case-studies/fuds-digital-platform/hero.png',
    gallery: [
      { src: '/images/case-studies/fuds-digital-platform/gallery-01.png', alt: 'Fuds website homepage', caption: 'Homepage with trust signals, pricing, and service listings' },
      { src: '/images/case-studies/fuds-digital-platform/gallery-02.png', alt: 'Booking form', caption: 'Simplified 4-field booking flow — 2.5× submission lift' },
      { src: '/images/case-studies/fuds-digital-platform/gallery-03.png', alt: 'Service listing page', caption: 'Service detail page with upfront pricing and technician credentials' },
    ],
    liveUrl: 'https://fuds.in',
    figmaUrl: 'https://www.figma.com/proto/fuds-digital-platform',
    wireframes: [
      { src: '/images/case-studies/fuds-digital-platform/wireframes/wireframe-01.png', alt: 'Homepage wireframe', caption: 'Initial wireframe exploring information architecture' },
      { src: '/images/case-studies/fuds-digital-platform/wireframes/wireframe-02.png', alt: 'Booking flow wireframe', caption: 'Booking flow iterations to reduce friction' },
    ],
    techStack: ['Shopify', 'Google Analytics', 'Figma', 'WhatsApp API'],
    timeline: '3 months',
    team: '2 (me + 1 developer)',
  },
  {
    slug: 'fuds-field-service-dashboard',
    number: '02',
    title: 'Fuds Field Service Dashboard',
    subtitle: 'AI Operations Automation',
    type: 'Built & Shipped',
    domain: 'AI Automation · Operations',
    status: 'Live on AWS Amplify',
    color: '#166534',
    bgGradient: 'linear-gradient(160deg, #052e16 0%, #14532d 40%, #16a34a 100%)',
    accent: '#22c55e',
    lightBg: '#f0fdf4',
    tldr: 'After launching the Fuds website and generating 70 leads/month, the operations side was still manual and chaotic — 30+ minutes of coordination per order. I built and deployed an AI-automated field service dashboard solo, zero budget, using vibe coding. Shopify webhook → admin panel → instant WhatsApp to customer and technician. Coordination time: near zero.',
    problem: 'An 8-person company with no CRM, no dispatch tool, and no budget for either was handling growing lead volume with phone calls and WhatsApp messages. With leads growing from 20 to 70/month after the website launch, this manual process was becoming a critical bottleneck.',
    role: [
      'Solo product owner + builder',
      'System design and workflow architecture',
      'Vibe coded the dashboard using Claude + Antigravity',
      'Shopify webhook integration setup',
      'WhatsApp Business API configuration',
      'AWS Amplify deployment',
    ],
    research: 'Identified the operations problem independently while tracking the post-inquiry journey. Observation: customers who received a fast, professional response were significantly more likely to convert and return.',
    solution: 'Automated flow: Customer submits booking → Shopify webhook fires → Dashboard receives order in real-time → Admin assigns technician with one tap → Customer receives WhatsApp (technician name, Aadhaar-verified credentials, ETA) + Technician receives WhatsApp (customer details, service info). Stack: Claude + Antigravity, Shopify Webhooks, WhatsApp Business API, AWS Amplify, Cognito, AppSync GraphQL.',
    results: [
      { metric: 'Order coordination time', before: '~30 min/order', after: 'Near zero' },
      { metric: 'Customer confirmation speed', before: 'Hours', after: 'Seconds' },
      { metric: 'Technician briefing', before: 'Phone call required', after: 'Automatic' },
      { metric: 'Human error in assignment', before: 'Frequent', after: 'Eliminated' },
      { metric: 'Repeat customer retention', before: 'Unmeasured', after: '~40%' },
    ],
    learnings: [
      'Constraints produce better product decisions — no budget forced a more elegant solution than a full CRM',
      'The confirmation moment is a product feature — automating the 60 seconds after submission with verified information was the highest-leverage intervention',
      'Vibe coding is a legitimate PM superpower — building solo with AI tools took weeks, not months',
    ],
    pdfFile: '/pdfs/02-Fuds-Field-Service-Dashboard.pdf',
    prdFile: '/pdfs/prds/06-Field-Service-Management-Platform.pdf',
    heroImage: '/images/case-studies/fuds-field-service-dashboard/hero.png',
    gallery: [
      { src: '/images/case-studies/fuds-field-service-dashboard/gallery-01.png', alt: 'Dashboard overview', caption: 'Order management dashboard with real-time status' },
      { src: '/images/case-studies/fuds-field-service-dashboard/gallery-02.png', alt: 'Technician assignment', caption: 'One-tap technician assignment with WhatsApp notification' },
      { src: '/images/case-studies/fuds-field-service-dashboard/gallery-03.png', alt: 'Analytics view', caption: 'Performance analytics and order tracking' },
    ],
    liveUrl: 'https://admin.fuds.in',
    embedUrl: 'https://admin.fuds.in',
    figmaUrl: 'https://www.figma.com/proto/fuds-field-service',
    wireframes: [
      { src: '/images/case-studies/fuds-field-service-dashboard/wireframes/wireframe-01.png', alt: 'Dashboard wireframe', caption: 'Initial concept for the operations dashboard' },
      { src: '/images/case-studies/fuds-field-service-dashboard/wireframes/wireframe-02.png', alt: 'Order flow wireframe', caption: 'Order assignment flow before building' },
    ],
    techStack: ['React', 'AWS Amplify', 'Cognito', 'AppSync', 'DynamoDB', 'WhatsApp API'],
    timeline: '6 weeks',
    team: 'Solo',
  },
  {
    slug: 'highprobtrade-stock-platform',
    number: '03',
    title: 'HighProbTrade',
    subtitle: 'AI Stock Analysis Platform',
    type: 'Client Project',
    domain: 'Fintech · AI',
    status: 'Testing Phase',
    color: '#4c1d95',
    bgGradient: 'linear-gradient(160deg, #1a0033 0%, #3b0764 40%, #7c3aed 100%)',
    accent: '#f59e0b',
    lightBg: '#f5f3ff',
    tldr: 'Retail NSE F&O traders face information overload — 188 stocks, scattered tools, no AI interpretation. I built a 4-phase smart scanner that narrows from market macro → sector heatmap → PDH/PDL filter → deep OI analytics, delivering 2–6 high-quality trade setups from 188 stocks. Built solo with vibe coding.',
    problem: 'Existing tools gave traders raw option chain data with no interpretation. To find a tradeable setup, a retail trader had to manually scan 188+ F&O stocks, cross-reference Open Interest changes, assess market sentiment, and identify intraday breakout setups — all before the trading window closed.',
    role: [
      'Solo product owner + full-stack builder (vibe coding)',
      'Product strategy and roadmap',
      'React 19 + Vite + Firebase + Gemini AI Studio',
      'NSE real-time data integration via Socket.io',
      'Vercel deployment',
    ],
    research: 'Interviewed retail F&O traders. Key pain points: information overload, delayed data (15-min delay on free tools), no context on raw OI numbers, no prioritisation — traders wasted time on low-probability setups.',
    solution: '4-Phase Smart Scanner: Phase 1 — Market Macro View (live quotes for 188 F&O stocks, Advances vs Declines), Phase 2 — Sector Heatmap (14 named sectors ranked by change), Phase 3 — PDH/PDL Master Filter, Phase 4 — Deep Analytics (full OI Chain, PCR, Max Pain, RSI/MACD/EMA, AI Insight per stock via Gemini). Additional features: Nifty OI Tracker with 15-min polling, Intraday Breakout Detection, OI Visualisation with support/resistance levels.',
    results: [
      { metric: 'Stocks scanned per cycle', before: 'Manual (188 stocks)', after: 'Automated (188 → 2–6 setups)' },
      { metric: 'Daily screening time', before: '45+ minutes', after: '3 minutes' },
      { metric: 'Real-time data delay', before: '15 minutes (free tools)', after: 'Real-time (Socket.io)' },
      { metric: 'Sentiment analysis', before: 'Manual cross-referencing', after: 'AI-driven (5-level)' },
    ],
    learnings: [
      'The gap was not more data — it was signal extraction from existing data',
      'AI sentiment with confidence scoring bridges the trust gap for retail traders',
      'A structured scanning methodology (macro → micro) outperforms raw data dashboards',
    ],
    pdfFile: '/pdfs/03-HighProbTrade-Stock-Platform.pdf',
    prdFile: '/pdfs/prds/03-Live-Stock-Options-Trading-Scanner.pdf',
    heroImage: '/images/case-studies/highprobtrade-stock-platform/hero.png',
    gallery: [
      { src: '/images/case-studies/highprobtrade-stock-platform/gallery-01.png', alt: 'Market macro view', caption: 'Phase 1 — Live market overview with advances vs declines' },
      { src: '/images/case-studies/highprobtrade-stock-platform/gallery-02.png', alt: 'Sector heatmap', caption: 'Phase 2 — Sector heatmap ranked by performance' },
      { src: '/images/case-studies/highprobtrade-stock-platform/gallery-03.png', alt: 'Deep analytics', caption: 'Phase 4 — Full OI chain with AI-driven sentiment analysis' },
    ],
    liveUrl: 'https://highprobtrade.vercel.app',
    embedUrl: 'https://highprobtrade.vercel.app',
    wireframes: [
      { src: '/images/case-studies/highprobtrade-stock-platform/wireframes/wireframe-01.png', alt: 'Scanner concept wireframe', caption: 'Initial 4-phase scanner concept' },
      { src: '/images/case-studies/highprobtrade-stock-platform/wireframes/wireframe-02.png', alt: 'Analytics layout wireframe', caption: 'Deep analytics page layout exploration' },
    ],
    techStack: ['React', 'Firebase', 'Gemini AI Studio', 'Socket.io', 'NSE API'],
    timeline: '2 months',
    team: 'Solo',
  },
  {
    slug: 'ai-marketing-compliance',
    number: '04',
    title: 'AI Marketing Compliance Platform',
    subtitle: 'IRDAI Compliance Scanning',
    type: 'Client Project',
    domain: 'InsurTech · AI · Regulatory',
    status: 'PRD Delivered',
    color: '#991b1b',
    bgGradient: 'linear-gradient(160deg, #450a0a 0%, #7f1d1d 40%, #dc2626 100%)',
    accent: '#f97316',
    lightBg: '#fef2f2',
    tldr: 'Insurance marketing teams face 3–5 day compliance review cycles with ~8% violation miss rate. Defined an AI-powered platform that scans marketing assets against a 12-rule engine (IRDAI, brand, legal) with bounding-box violation overlays — reducing review cycles from 3.8 days to 4 hours with 99.5% detection accuracy.',
    problem: 'Every marketing asset must comply with 12+ rules before publication. Manual compliance review takes 3–5 days, is error-prone, creates operational drag, and exposes the company to IRDAI penalties of ₹5–25 Lakh per violation.',
    role: [
      'Product strategy and PRD authorship',
      'User research with 3 personas (Marketing Manager, Compliance Officer, CMO)',
      'Market sizing: TAM ₹120 Cr, SAM ₹18 Cr, SOM ₹4.5 Cr',
      'Competitive analysis across 5 competitor categories',
      'RICE prioritisation and roadmap definition',
    ],
    research: 'Identified three user personas with distinct pain points: Marketing Managers losing campaign windows, Compliance Officers experiencing eye fatigue from manual review, and CMOs unable to audit historical compliance decisions.',
    solution: 'Core capability: Upload asset → AI scans against 12-rule compliance engine → Returns violations with bounding-box overlays and severity ratings. 12-Rule Engine covers IRDAI mandatory disclosures, brand guideline violations, and legal language requirements. Architecture: Next.js 16 frontend, Python FastAPI backend, AWS S3 storage, Upstash Redis for scan queue.',
    results: [
      { metric: 'Review cycle time', before: '3.8 days', after: '4 hours' },
      { metric: 'Violation detection rate', before: '92%', after: '99.5%' },
      { metric: 'Review capacity', before: '15 assets/week', after: '80 assets/week' },
      { metric: 'Annual value (FTE savings)', before: '4 FTEs', after: '1.5 FTEs (₹21L/yr)' },
    ],
    learnings: [
      'Domain-specific AI (IRDAI rules) creates a moat that generic tools cannot easily cross',
      'Bounding-box violation overlays are a UX differentiator — showing where, not just what',
      'An immutable audit trail is essential for regulatory credibility',
    ],
    pdfFile: '/pdfs/04-AI-Marketing-Compliance-Platform.pdf',
    prdFile: '/pdfs/prds/01-AI-Marketing-Compliance-Platform.pdf',
    heroImage: '/images/case-studies/ai-marketing-compliance/hero.png',
    gallery: [
      { src: '/images/case-studies/ai-marketing-compliance/gallery-01.png', alt: 'Compliance dashboard', caption: 'Dashboard showing scan status and violation overview' },
      { src: '/images/case-studies/ai-marketing-compliance/gallery-02.png', alt: 'Violation detection', caption: 'Bounding-box violation overlays on marketing assets' },
    ],
    figmaUrl: 'https://www.figma.com/proto/ai-compliance-platform',
    techStack: ['Next.js 16', 'Python FastAPI', 'OpenCV', 'Tesseract OCR', 'AWS S3', 'Upstash Redis'],
    timeline: '4 weeks (PRD phase)',
    team: 'Solo (strategy + PRD)',
  },
  {
    slug: 'compliance-qa-simulation',
    number: '05',
    title: 'Compliance QA Simulation Tool',
    subtitle: 'Zero-Dependency Browser Prototype',
    type: 'Client Project',
    domain: 'RegTech · AI Prototyping',
    status: 'Built & Delivered',
    color: '#92400e',
    bgGradient: 'linear-gradient(160deg, #431407 0%, #78350f 40%, #d97706 100%)',
    accent: '#06b6d4',
    lightBg: '#fffbeb',
    tldr: 'Before committing engineering resources to a full-stack compliance platform, the client needed stakeholder buy-in. I built a zero-dependency browser prototype in vanilla HTML/CSS/JS using vibe coding that simulated the complete user experience — used in 3 feedback sessions, leading to a feature redesign and greenlight for full-stack investment.',
    problem: 'The client needed to validate an AI compliance scanning concept with internal stakeholders before committing to full-stack development. The risk: building a full platform based on assumptions nobody had tested with real users.',
    role: ['Solo builder using vibe coding', 'System design and UX simulation', 'Vanilla HTML/CSS/JS development'],
    research: 'Identified the build-before-validating trap: many products fail because teams spend months building before showing to stakeholders. By the time feedback arrives, the cost of change is high.',
    solution: 'A fully functional simulation with 4 components: Dashboard (overview of scan status, pending reviews, violation count), Checklist Builder (drag-and-drop rule configuration), Progress Animation (visual AI processing simulation), Audit Log (timestamped compliance decisions). Zero dependencies — runs as a single HTML file.',
    results: [
      { metric: 'Stakeholder feedback sessions', before: '0', after: '3' },
      { metric: 'Checklist builder redesign', before: 'Original design', after: 'Redesigned based on feedback' },
      { metric: 'Audit log priority', before: 'Not in scope', after: 'Added as high priority' },
      { metric: 'Investment decision', before: 'Undecided', after: 'Greenlit full-stack build' },
    ],
    learnings: [
      'A prototype is a risk-reduction tool, not a shortcut — build to validate, not to skip building',
      'Zero-dependency prototypes remove adoption friction — stakeholders opened it in any browser with no setup',
      'Simulated UIs reveal real feedback that slide decks never surface',
    ],
    pdfFile: '/pdfs/05-Compliance-QA-Simulation-Tool.pdf',
    prdFile: '/pdfs/prds/09-Compliance-QA-Simulation-Tool.pdf',
    heroImage: '/images/case-studies/compliance-qa-simulation/hero.png',
    prototypeUrl: 'https://compliance-qa-sim.netlify.app',
    embedUrl: 'https://compliance-qa-sim.netlify.app',
    techStack: ['HTML', 'CSS', 'JavaScript', 'Tabler Icons'],
    timeline: '1 week',
    team: 'Solo',
  },
  {
    slug: 'saas-dashboard-ux-redesign',
    number: '06',
    title: 'SaaS Dashboard UX Redesign',
    subtitle: 'Mobile-First Activation Journey',
    type: 'Client Project',
    domain: 'SaaS · UX Research',
    status: 'Delivered',
    color: '#9d174d',
    bgGradient: 'linear-gradient(160deg, #4a0e2b 0%, #831843 40%, #db2777 100%)',
    accent: '#818cf8',
    lightBg: '#fdf2f8',
    tldr: 'An early-stage SaaS product had strong acquisition but poor activation — users signed up, logged in, looked at the dashboard, and left. I evaluated the dashboard against Nielsen\'s heuristics, mapped user flows, benchmarked 5 competitors, and redesigned a 6-screen mobile journey targeting +40% activation and +25% D7 retention.',
    problem: 'Day-7 retention was below target and feature discovery was near zero. Users couldn\'t find the path to value — the dashboard had 14 data points on the home screen creating cognitive overload, no onboarding guidance, and a desktop-first design despite 60% mobile traffic.',
    role: [
      'UX research: heuristic evaluation, user flow mapping, competitive benchmarking',
      'Interaction design and mobile-first redesign',
      'Success metrics definition and KPI tracking framework',
    ],
    research: 'Evaluated against Nielsen\'s 10 usability heuristics. Key violations: visibility of system status, match with real world, recognition vs recall, aesthetic/minimalist design. Analysed 5 competing SaaS products for onboarding and dashboard patterns. Mapped user journey — most users never reached the core feature (3+ clicks required).',
    solution: '6-Screen Mobile Journey: Screen 1 — Conversational Onboarding (AI-driven, 3 questions), Screen 2 — Personalised Home (3 primary actions based on responses), Screen 3 — Business Chat (AI assistant), Screen 4 — Feature Discovery (contextual prompts based on behaviour), Screen 5 — Progress Tracking (visual milestone tracker), Screen 6 — Mobile-First Navigation (bottom nav, thumb-friendly).',
    results: [
      { metric: 'Activation rate', before: 'Low', after: '+40% (target)' },
      { metric: 'Feature discovery (session 1)', before: 'Low', after: '+60% (target)' },
      { metric: 'Day-7 retention', before: 'Below target', after: '+25% (target)' },
      { metric: 'Mobile session completion', before: 'Low', after: '+50% (target)' },
    ],
    learnings: [
      'Activation problems are almost always information architecture problems in disguise',
      'Users don\'t fail to activate because they lack motivation — they fail because they can\'t find the path to value',
      'Mobile-first design is not optional when 60% of traffic comes from mobile',
    ],
    pdfFile: '/pdfs/06-SaaS-Dashboard-UX-Redesign.pdf',
    prdFile: '/pdfs/prds/07-SaaS-Dashboard-UX-Redesign.pdf',
    heroImage: '/images/case-studies/saas-dashboard-ux-redesign/hero.png',
    figmaUrl: 'https://www.figma.com/proto/saas-dashboard-redesign',
    techStack: ['Figma', 'UX Research', 'Prototyping', 'Mobile-First Design'],
    timeline: '3 weeks',
    team: 'Solo (consultant)',
  },
  {
    slug: 'trading-education-landing',
    number: '07',
    title: 'Trading Education Landing Page',
    subtitle: 'High-Conversion Lead Capture',
    type: 'Client Project',
    domain: 'Fintech · Growth Marketing',
    status: 'Live (Testing Phase)',
    color: '#155e75',
    bgGradient: 'linear-gradient(160deg, #082f49 0%, #164e63 40%, #0891b2 100%)',
    accent: '#10b981',
    lightBg: '#ecfeff',
    tldr: 'Converted cold digital traffic into verified leads for a trading education platform. Designed a 5-section landing page with email OTP verification (Firebase), two-tier pricing (₹4,999/₹9,999), and an AI Demo section that demonstrates value before asking for commitment.',
    problem: 'Trading education is a high-trust, high-scepticism category. Users have been burned by low-quality courses and approach new platforms with distrust. Getting a form submission requires more than a good headline.',
    role: [
      'Conversion architecture design',
      'Competitive analysis of 8 fintech education landing pages',
      'Firebase email OTP integration planning',
      'Metrics and tracking framework',
    ],
    research: 'Analysed 8 fintech education pages for: trust signal placement, CTA copy, pricing patterns, social proof format, form friction. Pattern: high-converting pages lead with a specific, verifiable claim — not a generic promise.',
    solution: '5-Section Conversion Architecture: Hero (AI capability claim + 3 stat cards), Features/Screenshots (carousel of 4 platform features), AI Demo (realistic trade analysis card with sentiment, confidence %, entry/target/stop-loss), Pricing (two clear plans with feature comparison), Lead Capture (email OTP verification, 3 fields only). Stack: React 19 + Vite 6, Tailwind CSS 4, Firebase Auth + Firestore, Vercel.',
    results: [
      { metric: 'Lead quality', before: 'Unverified emails', after: 'OTP-verified, high intent' },
      { metric: 'Pricing complexity', before: '3 tiers (decision paralysis)', after: '2 tiers (simple anchor)' },
      { metric: 'Value demonstration', before: 'Generic promises', after: 'Specific AI trade analysis demo' },
    ],
    learnings: [
      'Email OTP trades conversion volume for lead quality — the right trade for high-ticket products (₹4,999+)',
      'Showing value before price converts the question from "should I pay?" to "how much does it cost?"',
      'Two tiers beat three — decision paralysis is real in pricing',
    ],
    pdfFile: '/pdfs/07-Trading-Education-Landing-Page.pdf',
    prdFile: '/pdfs/prds/05-Trading-Education-Landing-Page.pdf',
    heroImage: '/images/case-studies/trading-education-landing/hero.png',
    liveUrl: 'https://trading-education.vercel.app',
    embedUrl: 'https://trading-education.vercel.app',
    techStack: ['React 19', 'Vite 6', 'Firebase Auth', 'Firestore', 'Tailwind CSS 4'],
    timeline: '2 weeks',
    team: 'Solo',
  },
  {
    slug: 'laundry-pos-system',
    number: '08',
    title: 'Laundry POS & Management System',
    subtitle: 'AI-Powered SMB Operations',
    type: 'Product Spec',
    domain: 'SMB · AI · Retail Operations',
    status: 'Full PRD',
    color: '#065f46',
    bgGradient: 'linear-gradient(160deg, #022c22 0%, #064e3b 40%, #059669 100%)',
    accent: '#f59e0b',
    lightBg: '#f0fdfa',
    tldr: 'India has 5M+ unorganised laundry businesses running on paper and memory — leading to lost orders, no customer history, and pickup disputes. Designed an AI-powered POS system with a 4-step order wizard, Claude Vision stain detection, Morning Briefing dashboard, and Agentic Chat POS.',
    problem: 'The vast majority of Indian laundry businesses run entirely on memory and paper: no order tracking, no customer history, no inventory visibility, no CRM. The core problem: no system of record means every operational failure is invisible until it becomes a customer complaint.',
    role: [
      'Product strategy and spec authorship',
      'User research with 3 business segments',
      'RICE prioritisation and MoSCoW MVP definition',
      'Market sizing (TAM ~5M businesses, SAM ~500K)',
    ],
    research: 'Interviewed laundry operators across three segments: single-operator dhobi, growing laundry shop (2–5 staff), laundry chain (5+ locations). Common pain points: lost orders (very high frequency), no customer history, manual stain assessment leading to pickup disputes, no daily revenue visibility.',
    solution: '4 Core Modules: 1. 4-Step Order Wizard (customer identification → item entry → Claude Vision stain detection → pricing + token), 2. Morning Briefing Dashboard (orders due, revenue vs yesterday, pending pickups, inventory alerts), 3. Agentic Chat POS (natural language order entry), 4. Claude Vision Stain Detection (photo upload → AI assessment → treatment note + pricing). MVP: Order wizard + customer lookup + token generation + basic reporting.',
    results: [
      { metric: 'Order processing time', before: 'Manual/paper', after: '50% reduction (target)' },
      { metric: 'Pickup disputes', before: 'Frequent', after: '-70% (stain documentation)' },
      { metric: 'Repeat customer recognition', before: 'None', after: '90% accuracy' },
      { metric: 'Revenue per ticket', before: 'Inconsistent', after: '+15% accurate pricing' },
    ],
    learnings: [
      'SMB products in India must work offline-first and on budget devices — the operator\'s smartphone is often entry-level',
      'AI features (like stain detection) are differentiators, not core — the order wizard is the real product',
      'Natural language input (Agentic Chat POS) bridges the digital literacy gap for non-tech-savvy operators',
    ],
    pdfFile: '/pdfs/08-Laundry-POS-Management-System.pdf',
    prdFile: '/pdfs/prds/02-Laundry-POS-Management-System.pdf',
    heroImage: '/images/case-studies/laundry-pos-system/hero.png',
    techStack: ['React 18', 'Vite 6', 'Framer Motion', 'Recharts', 'Claude API', 'jsPDF'],
    timeline: 'PRD phase only',
    team: 'Solo',
  },
  {
    slug: 'ai-astrology-dashboard',
    number: '09',
    title: 'AI-Powered Astrology Dashboard',
    subtitle: 'Interactive Vedic Astrology Platform',
    type: 'Product Spec',
    domain: 'Consumer AI · B2C · Spiritual Tech',
    status: 'Full PRD',
    color: '#5b21b6',
    bgGradient: 'linear-gradient(160deg, #2e1065 0%, #4c1d95 40%, #8b5cf6 100%)',
    accent: '#f472b6',
    lightBg: '#f5f3ff',
    tldr: 'India has 200M+ regular astrology consumers, yet the product experience hasn\'t changed in decades — static PDF kundali reports, no interactivity, no real-time analysis. Designed an interactive Vedic astrology platform combining NASA JPL ephemeris data (professional-grade accuracy) with AI interpretations, a 60+ remedy engine, and interactive Q&A.',
    problem: 'The product experience for astrology consumers hasn\'t changed meaningfully in decades: static PDF kundali reports, generic interpretations not personalised to the user\'s current life situation, no interactivity, no real-time transit analysis, and generic remedies not contextualised to the individual chart.',
    role: [
      'Product strategy and spec authorship',
      '3 user personas: The Believer, The Curious, The Seeker',
      'RICE prioritisation and monetisation strategy',
      'Feature design: kundali engine, AI layer, Dasha timeline, remedy engine',
    ],
    research: 'Identified 3 user segments: The Believer (25–45F, urban, pays ₹500–2000/session for consultations), The Curious (20–35, sceptical but engaged, uses free apps), The Seeker (40–60F, semi-urban, high trust in Vedic system, low digital literacy).',
    solution: '5 Core Features: 1. Kundali Generation Engine (NASA JPL ephemeris for planet positions — professional astronomical accuracy), 2. AI Interpretation Layer (natural language interpretations contextualised to the user\'s chart and life questions), 3. Dasha Timeline (Mahadasha/Antardasha visualisation with forward-looking predictions), 4. 60+ Remedy Engine (personalised gemstones, mantras, fasting — contextualised to specific planetary afflictions), 5. Interactive Q&A (conversational AI that analyses dasha + transits + natal chart).',
    results: [
      { metric: 'Target market (TAM)', before: '—', after: '200M+ astrology consumers' },
      { metric: 'Monetisation tiers', before: 'Single static report', after: 'Free / ₹299 / ₹999 per month' },
      { metric: 'Astronomical accuracy', before: '±1° (simplified algorithms)', after: 'NASA JPL ephemeris (professional)' },
    ],
    learnings: [
      'Combining ancient knowledge (Vedic system) with scientific computation (NASA JPL) creates a defensible differentiator',
      'AI Q&A transforms a static report into an interactive experience — the real product innovation',
      'Three-tier monetisation (Free → Personal → Premium) with live consultation upsell mirrors proven consumer app models',
    ],
    pdfFile: '/pdfs/09-AI-Astrology-Dashboard.pdf',
    prdFile: '/pdfs/prds/04-AI-Astrology-Dashboard.pdf',
    heroImage: '/images/case-studies/ai-astrology-dashboard/hero.png',
    techStack: ['Next.js 16', 'TypeScript', 'Zustand', 'Groq API', 'NASA JPL Ephemeris'],
    timeline: 'PRD phase only',
    team: 'Solo',
  },
  {
    slug: 'edtech-communication-platform',
    number: '10',
    title: 'EdTech Student Communication Platform',
    subtitle: 'Unified Cohort Communication',
    type: 'Product Spec',
    domain: 'EdTech · Community · AI',
    status: 'Full PRD',
    color: '#0c4a6e',
    bgGradient: 'linear-gradient(160deg, #082f49 0%, #0c4a6e 40%, #0284c7 100%)',
    accent: '#fb923c',
    lightBg: '#f0f9ff',
    tldr: 'EdTech students manage communication across WhatsApp, Telegram, and LinkedIn — spending more time managing platforms than learning. Designed a unified 5-feature platform (Cohort Chat, AI Doubt Feed, Peer Profiles, AI Study Rooms, Alumni Bridge) with B2B SaaS pricing sold to edtech platforms.',
    problem: 'Cohort discussions happen on WhatsApp (ephemeral, noisy), doubt resolution on Telegram (inconsistent), networking on LinkedIn (not learning-contextual), and alumni connections don\'t happen at all. Students spend more time managing communication across platforms than learning.',
    role: [
      'Product strategy and spec authorship',
      'Surveyed 50+ students across 5 edtech platforms',
      'TAM-SAM-SOM market sizing',
      'RICE prioritisation and MoSCoW MVP definition',
      'B2B SaaS monetisation strategy',
    ],
    research: 'Surveyed 50+ edtech students across NextLeap, Scaler, UpGrad, Newton School, Masai. Key findings: 78% use 3+ platforms, 71% find doubt resolution slow, 84% feel disconnected from alumni, 38% cite communication friction as reason for dropout consideration.',
    solution: '5-Feature Unified Platform: 1. Cohort Chat (structured, searchable discussions by topic/week/assignment), 2. AI Doubt Feed (student posts doubt → AI answers from course content → routes to peer expert if needed), 3. Peer Profiles (learning-contextual profiles with skills, projects, focus areas), 4. AI Study Rooms (Pomodoro-aligned focused sessions with AI check-ins), 5. Alumni Bridge (structured pathway for alumni contribution + office hours).',
    results: [
      { metric: 'DAU in cohort', before: 'Fragmented', after: '>70% of enrolled (target)' },
      { metric: 'Doubt resolution time', before: '24+ hours (WhatsApp)', after: '<2 hours (target)' },
      { metric: 'Alumni participation', before: 'Near zero', after: '>30% active monthly (target)' },
      { metric: 'Course completion lift', before: 'Baseline', after: '+20% (target)' },
    ],
    learnings: [
      'The problem isn\'t that students don\'t want to learn — the friction of getting help is high enough that they give up',
      'B2B is the right GTM because edtech platforms already have the students — this enhances their retention metrics',
      'Every percentage point reduction in doubt resolution time is a percentage point improvement in course completion',
    ],
    pdfFile: '/pdfs/10-EdTech-Student-Communication-Platform.pdf',
    prdFile: '/pdfs/prds/08-EdTech-Student-Communication-Platform.pdf',
    heroImage: '/images/case-studies/edtech-communication-platform/hero.png',
    techStack: ['Product Strategy', 'UX Design', 'AI Integration', 'Market Research'],
    timeline: 'PRD phase only',
    team: 'Solo',
  },
]
